# Generated by Django 4.0.1 on 2022-02-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_remove_user_save_user_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCSvModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('RatingTomatometer', models.CharField(max_length=200)),
                ('Genres', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'MyCSvModel',
                'managed': True,
            },
        ),
    ]
