# Generated by Django 4.0.1 on 2022-02-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_delete_mycsvmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCSvModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('RatingTomatometer', models.IntegerField(default=0)),
                ('Genres', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'csvmodel1',
            },
        ),
    ]
