# Generated by Django 4.0.1 on 2022-02-09 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_mycsvmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycsvmodel',
            name='Genres',
        ),
        migrations.RemoveField(
            model_name='mycsvmodel',
            name='RatingTomatometer',
        ),
        migrations.RemoveField(
            model_name='mycsvmodel',
            name='title',
        ),
        migrations.AlterModelTable(
            name='mycsvmodel',
            table='csvmodel',
        ),
    ]
