# Generated by Django 4.0.1 on 2022-02-11 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0007_mycsvmodel_genres_mycsvmodel_ratingtomatometer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycsvmodel',
            name='Genres',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mycsvmodel',
            name='RatingTomatometer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mycsvmodel',
            name='Title',
            field=models.TextField(null=True),
        ),
    ]
