# Generated by Django 4.0.1 on 2022-02-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0008_alter_mycsvmodel_genres_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='moviep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference', models.CharField(default='#', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='mycsvmodel',
            name='Genres',
            field=models.CharField(default='#', max_length=300),
        ),
        migrations.AlterField(
            model_name='mycsvmodel',
            name='RatingTomatometer',
            field=models.CharField(default='#', max_length=300),
        ),
        migrations.AlterField(
            model_name='mycsvmodel',
            name='Title',
            field=models.CharField(default='#', max_length=300),
        ),
    ]
