# Generated by Django 4.0.1 on 2022-02-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0009_moviep_alter_mycsvmodel_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key',
            field=models.CharField(max_length=50),
        ),
    ]
