# Generated by Django 4.0.1 on 2022-02-16 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0010_alter_user_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='key',
            new_name='key1',
        ),
    ]
