# Generated by Django 4.0.1 on 2022-02-16 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0011_rename_key_user_key1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='key1',
            new_name='key',
        ),
    ]
